# Generated by Django 4.2.26 on 2025-11-14 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carmodel_cartype_remove_car_category_car_car_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars.carmodel', verbose_name='Car Model'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars.cartype', verbose_name='Car Type'),
        ),
    ]
