# Generated by Django 4.2.26 on 2025-11-14 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_car_model_alter_car_car_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='ac_price_per_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for AC variant (if car type is Both)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='non_ac_price_per_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for Non-AC variant (if car type is Both)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carmodel', verbose_name='Car Model'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.cartype', verbose_name='Car Type'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_per_km',
            field=models.DecimalField(decimal_places=2, help_text='Price for the default car type', max_digits=10),
        ),
    ]
