# Generated by Django 4.2.26 on 2025-11-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_ac_price_per_km_car_non_ac_price_per_km_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price_per_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for the default car type', max_digits=10, null=True),
        ),
    ]
