# Generated by Django 4.2.26 on 2025-11-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='car_models/'),
        ),
    ]
